services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    container_name: bazarr
    domainname: ${SUBDOMAIN_BAZARR}.${DOMAIN}
    ports:
      - 6767:6767
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${DATA_DIR}:/data
    depends_on:
      - decypharr

  decypharr:
    image: cy01/blackhole:latest
    restart: unless-stopped
    container_name: decypharr
    domainname: ${SUBDOMAIN_DECYPHARR}.${DOMAIN}
    ports:
      - 8282:8282
    volumes:
      - ${CONFIG_DIR}/decypharr:/app
      - ${DATA_DIR}/downloads:/data/downloads:rshared
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    container_name: jellyfin
    domainname: ${SUBDOMAIN_JELLYFIN}.${DOMAIN}
    ports:
      - 8096:8096/tcp
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${DATA_DIR}:/data:rslave
    depends_on:
      - radarr
      - sonarr

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    restart: unless-stopped
    container_name: jellyseerr
    domainname: ${SUBDOMAIN_JELLYSEER}.${DOMAIN}
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    depends_on:
      - prowlarr
      - radarr
      - sonarr

  # overseerr:
  #   image: lscr.io/linuxserver/overseerr:latest
  #   restart: unless-stopped
  #   container_name: overseerr
  #   domainname: ${SUBDOMAIN_OVERSEERR}.${DOMAIN}
  #   ports:
  #     - 5055:5055
  #   environment:
  #     - PUID=${ENV_PUID}
  #     - PGID=${ENV_PGID}
  #     - TZ=${TIMEZONE}
  #   volumes:
  #     - ${CONFIG_DIR}/overseerr:/app/config
  #   depends_on:
  #     - prowlarr
  #     - radarr
  #     - sonarr

  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   restart: unless-stopped
  #   container_name: qbittorrent
  #   domainname: ${SUBDOMAIN_QBITTORRENT}.${DOMAIN}
  #   ports:
  #     - 8080:8080 # Web UI port
  #     - 6881:6881 # Torrent port TCP
  #     - 6881:6881/udp # Torrent port UDP
  #   environment:
  #     - PUID=${ENV_PUID}
  #     - PGID=${ENV_PGID}
  #     - TZ=${TIMEZONE}
  #     - WEBUI_PORT=8080
  #     - TORRENTING_PORT=6881
  #   volumes:
  #     - ${CONFIG_DIR}/qbittorrent:/config
  #     - ${DATA_DIR}/downloads:/data/downloads

  # plex:
  #   image: lscr.io/linuxserver/plex:latest
  #   restart: unless-stopped
  #   container_name: plex
  #   ports:
  #     - 32400:32400/tcp
  #   environment:
  #     - PUID=${ENV_PUID}
  #     - PGID=${ENV_PGID}
  #     - TZ=${TIMEZONE}
  #     - VERSION=docker
  #   volumes:
  #     - ${CONFIG_DIR}/plex:/config
  #     - ${DATA_DIR}/media:/data/media
  #   network_mode: host
  #   depends_on:
  #     - rclone

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    container_name: prowlarr
    domainname: ${SUBDOMAIN_PROWLARR}.${DOMAIN}
    ports:
      - 9696:9696
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    depends_on:
      - decypharr
      # - rclone

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    domainname: ${SUBDOMAIN_RADARR}.${DOMAIN}
    ports:
      - 7878:7878
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DATA_DIR}:/data
    depends_on:
      - decypharr
      # - rclone

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    restart: unless-stopped
    container_name: recyclarr
    user: ${ENV_PUID}:${ENV_PGID}
    environment:
      - TZ=${TIMEZONE}
      - RECYCLARR_CREATE_CONFIG=true
    volumes:
      - ${CONFIG_DIR}/recyclarr:/config
    security_opt: ["no-new-privileges:true"]
    depends_on:
      - radarr
      - sonarr

  # rclone:
  #   image: rclone/rclone:latest
  #   restart: unless-stopped
  #   container_name: rclone
  #   environment:
  #     - PUID=${ENV_PUID}
  #     - PGID=${ENV_PGID}
  #     - TZ=${TIMEZONE}
  #   volumes:
  #     - ${CONFIG_DIR}/rclone/rclone.conf:/config/rclone/rclone.conf
  #     - ${ROOT_DIR}/data/downloads:/data:rshared
  #     - ./rclone.conf:/config/rclone/rclone.conf
  #   devices:
  #     - /dev/fuse:/dev/fuse:rwm
  #   cap_add:
  #     - SYS_ADMIN
  #   depends_on:
  #     - zurg
  #   command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    domainname: ${SUBDOMAIN_SONARR}.${DOMAIN}
    ports:
      - 8989:8989
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DATA_DIR}:/data
    depends_on:
      - decypharr
      # - rclone

  # zurg:
  #   image: ghcr.io/debridmediamanager/zurg-testing:latest
  #   restart: unless-stopped
  #   container_name: zurg
  #   ports:
  #     - 9999:9999
  #   volumes:
  #     - ${CONFIG_DIR}/zurg/config.yml:/app/config.yml
  #     - ${DATA_DIR}/downloads:/app/data
